repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier
        exclude: src/furo/theme/.*|docs/(recommendations|reference/admonitions).md

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3.8

  - repo: https://github.com/asottile/blacken-docs
    rev: v1.10.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==20.8b1]

  - repo: https://github.com/PyCQA/isort
    rev: 5.8.0
    hooks:
      - id: isort
        files: \.py$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-builtin-literals
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: forbid-new-submodules
      - id: trailing-whitespace

  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.1
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
      - id: mypy
        args: [--disallow-untyped-defs, --ignore-missing-imports]
        files: src/.*\.py$

  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.0.0
    hooks:
      - id: pydocstyle
        files: src/.*\.py$
